// Datos de demostración — reflejan supabase/seed.sql. Se usan como respaldo
// local (`isDemoMode`) mientras el proyecto Supabase real no está conectado,
// para poder construir y probar la UI de ambas apps desde ya. Reemplazar por
// datos reales apenas se provisione el backend (ver docs/NEXT_STEPS.md).
import type { EstablishmentWithDetails, AdoptionPostWithPhotos, EstablishmentHours } from './types';

function fullWeekHours(establishmentId: string, is24h: boolean, sundayClosed = true): EstablishmentHours[] {
  return Array.from({ length: 7 }, (_, day_of_week) => ({
    id: `${establishmentId}-h${day_of_week}`,
    establishment_id: establishmentId,
    day_of_week,
    open_time: is24h ? '00:00' : '08:00:00',
    close_time: is24h ? '23:59' : '18:00:00',
    closed: !is24h && sundayClosed && day_of_week === 0,
  }));
}

export const DEMO_ESTABLISHMENTS: EstablishmentWithDetails[] = [
  {
    id: '00000000-0000-4000-a000-000000000001',
    owner_id: null,
    name: 'Veterinaria Central Ibagué',
    slug: 'veterinaria-central-ibague',
    category: 'veterinaria',
    description: 'Atención general, urgencias y hospitalización. Más de 10 años atendiendo el centro de la ciudad.',
    address: 'Calle 15 # 3-20, Centro',
    city: 'Ibagué',
    lat: 4.4389,
    lng: -75.2322,
    phone: '6082601234',
    whatsapp_number: '573001234501',
    email: null,
    website: null,
    is_24_7: true,
    is_active: true,
    verification_status: 'verificado',
    verification_notes: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('1', true),
    services: [
      { id: 's1', establishment_id: '1', name: 'Consulta general', description: 'Valoración clínica completa', price_reference: 'desde $50.000', duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
      { id: 's2', establishment_id: '1', name: 'Vacunación', description: 'Esquema completo perros y gatos', price_reference: 'desde $35.000', duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: '00000000-0000-4000-a000-000000000002',
    owner_id: null,
    name: 'Clínica Veterinaria Pata Amiga',
    slug: 'clinica-pata-amiga',
    category: 'veterinaria',
    description: 'Consulta general, vacunación, cirugía y odontología veterinaria.',
    address: 'Carrera 5 # 42-10, Belén',
    city: 'Ibagué',
    lat: 4.4512,
    lng: -75.2101,
    phone: '6082605678',
    whatsapp_number: '573001234502',
    email: null,
    website: null,
    is_24_7: false,
    is_active: true,
    verification_status: 'verificado',
    verification_notes: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('2', false),
    services: [
      { id: 's3', establishment_id: '2', name: 'Cirugía menor', description: 'Esterilización y procedimientos ambulatorios', price_reference: 'desde $180.000', duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: '00000000-0000-4000-a000-000000000003',
    owner_id: null,
    name: 'Veterinaria y Urgencias 24H Tolima',
    slug: 'veterinaria-urgencias-24h-tolima',
    category: 'veterinaria',
    description: 'Atención de urgencias las 24 horas, todos los días.',
    address: 'Avenida Ambalá # 20-45',
    city: 'Ibagué',
    lat: 4.4601,
    lng: -75.2287,
    phone: '6082609876',
    whatsapp_number: '573001234503',
    email: null,
    website: null,
    is_24_7: true,
    is_active: true,
    verification_status: 'verificado',
    verification_notes: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('3', true),
    services: [
      { id: 's4', establishment_id: '3', name: 'Urgencia 24H', description: 'Atención inmediata cualquier hora del día', price_reference: 'desde $80.000', duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: '00000000-0000-4000-a000-000000000004',
    owner_id: null,
    name: 'PetShop La 19',
    slug: 'petshop-la-19',
    category: 'comercio',
    description: 'Alimentos, accesorios, juguetes e higiene para perros y gatos.',
    address: 'Carrera 4 # 19-30',
    city: 'Ibagué',
    lat: 4.437,
    lng: -75.2005,
    phone: '6082611122',
    whatsapp_number: '573001234504',
    email: null,
    website: null,
    is_24_7: false,
    is_active: true,
    verification_status: 'verificado',
    verification_notes: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('4', false),
    services: [
      { id: 's5', establishment_id: '4', name: 'Venta de alimento concentrado', description: 'Marcas premium y económicas', price_reference: null, duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: '00000000-0000-4000-a000-000000000006',
    owner_id: null,
    name: 'Estética Canina Huellitas',
    slug: 'estetica-canina-huellitas',
    category: 'comercio',
    description: 'Baño, corte y spa canino/felino con cita previa.',
    address: 'Calle 42 # 6-15, Belén',
    city: 'Ibagué',
    lat: 4.453,
    lng: -75.209,
    phone: '6082615566',
    whatsapp_number: '573001234506',
    email: null,
    website: null,
    is_24_7: false,
    is_active: true,
    verification_status: 'verificado',
    verification_notes: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('6', false),
    services: [
      { id: 's6', establishment_id: '6', name: 'Baño y corte', description: 'Spa completo con productos hipoalergénicos', price_reference: 'desde $40.000', duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: '00000000-0000-4000-a000-000000000007',
    owner_id: null,
    name: 'Dra. Camila Rojas · Medicina Veterinaria',
    slug: 'dra-camila-rojas-veterinaria',
    category: 'profesional',
    description: 'Consulta a domicilio y medicina alternativa veterinaria.',
    address: 'Zona norte de Ibagué (atención a domicilio)',
    city: 'Ibagué',
    lat: 4.468,
    lng: -75.221,
    phone: '6082617788',
    whatsapp_number: '573001234507',
    email: null,
    website: null,
    is_24_7: false,
    is_active: true,
    verification_status: 'verificado',
    verification_notes: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('7', false),
    services: [
      { id: 's7', establishment_id: '7', name: 'Consulta a domicilio', description: 'Visita veterinaria en tu hogar', price_reference: 'desde $70.000', duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: '00000000-0000-4000-a000-000000000008',
    owner_id: null,
    name: 'Guardería y Entrenamiento CanApp',
    slug: 'guarderia-entrenamiento-canapp',
    category: 'comercio',
    description: 'Guardería diurna, paseos y entrenamiento básico de obediencia.',
    address: 'Carrera 12 # 55-08',
    city: 'Ibagué',
    lat: 4.455,
    lng: -75.198,
    phone: '6082619900',
    whatsapp_number: '573001234508',
    email: null,
    website: null,
    is_24_7: false,
    is_active: true,
    verification_status: 'pendiente',
    verification_notes: null,
    verified_at: null,
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('8', false),
    services: [
      { id: 's8', establishment_id: '8', name: 'Guardería diurna', description: 'Cuidado y socialización por día', price_reference: 'desde $30.000', duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: '00000000-0000-4000-a000-000000000009',
    owner_id: null,
    name: 'Fundación Huellas de Esperanza Tolima',
    slug: 'fundacion-huellas-esperanza-tolima',
    category: 'fundacion',
    description: 'Rescate, esterilización y adopción responsable de perros y gatos en Ibagué.',
    address: 'Zona sur de Ibagué',
    city: 'Ibagué',
    lat: 4.418,
    lng: -75.226,
    phone: '6082622233',
    whatsapp_number: '573001234509',
    email: null,
    website: null,
    is_24_7: false,
    is_active: true,
    verification_status: 'verificado',
    verification_notes: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('9', false),
    services: [],
  },
  {
    id: '00000000-0000-4000-a000-000000000010',
    owner_id: null,
    name: 'Refugio Patitas Sin Hogar',
    slug: 'refugio-patitas-sin-hogar',
    category: 'fundacion',
    description: 'Refugio independiente enfocado en animales en condición de calle y adopciones.',
    address: 'Vereda La Vega, Ibagué',
    city: 'Ibagué',
    lat: 4.405,
    lng: -75.24,
    phone: '6082624455',
    whatsapp_number: '573001234510',
    email: null,
    website: null,
    is_24_7: false,
    is_active: true,
    verification_status: 'verificado',
    verification_notes: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('10', false),
    services: [],
  },
];

export const DEMO_ADOPTION_POSTS: AdoptionPostWithPhotos[] = [
  {
    id: '00000000-0000-4000-b000-000000000001',
    posted_by: null,
    establishment_id: '00000000-0000-4000-a000-000000000009',
    animal_name: 'Luna',
    species: 'perro',
    estimated_age: '2 años aprox.',
    sex: 'hembra',
    sterilized: true,
    vaccinated: true,
    health_notes: 'Esterilizada y con esquema de vacunación completo.',
    personality_notes: 'Tranquila, sociable con niños y otros perros.',
    location_text: 'Ibagué, zona sur',
    status: 'disponible',
    cover_photo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    photos: [],
    establishment: { id: '9', name: 'Fundación Huellas de Esperanza Tolima', slug: 'fundacion-huellas-esperanza-tolima', whatsapp_number: '573001234509' },
  },
  {
    id: '00000000-0000-4000-b000-000000000002',
    posted_by: null,
    establishment_id: '00000000-0000-4000-a000-000000000009',
    animal_name: 'Simón',
    species: 'gato',
    estimated_age: '8 meses aprox.',
    sex: 'macho',
    sterilized: false,
    vaccinated: true,
    health_notes: 'Vacunado, pendiente de esterilización.',
    personality_notes: 'Juguetón, se adapta bien a apartamentos.',
    location_text: 'Ibagué, zona sur',
    status: 'disponible',
    cover_photo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    photos: [],
    establishment: { id: '9', name: 'Fundación Huellas de Esperanza Tolima', slug: 'fundacion-huellas-esperanza-tolima', whatsapp_number: '573001234509' },
  },
  {
    id: '00000000-0000-4000-b000-000000000003',
    posted_by: null,
    establishment_id: '00000000-0000-4000-a000-000000000010',
    animal_name: 'Toby',
    species: 'perro',
    estimated_age: 'Cachorro (3 meses)',
    sex: 'macho',
    sterilized: false,
    vaccinated: false,
    health_notes: 'En proceso de primera vacunación.',
    personality_notes: 'Muy activo, requiere hogar con espacio.',
    location_text: 'Vereda La Vega, Ibagué',
    status: 'disponible',
    cover_photo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    photos: [],
    establishment: { id: '10', name: 'Refugio Patitas Sin Hogar', slug: 'refugio-patitas-sin-hogar', whatsapp_number: '573001234510' },
  },
  {
    id: '00000000-0000-4000-b000-000000000004',
    posted_by: null,
    establishment_id: '00000000-0000-4000-a000-000000000010',
    animal_name: 'Mora',
    species: 'gato',
    estimated_age: '1 año aprox.',
    sex: 'hembra',
    sterilized: true,
    vaccinated: true,
    health_notes: 'Esterilizada, esquema de vacunación al día.',
    personality_notes: 'Independiente, ideal para hogar tranquilo.',
    location_text: 'Vereda La Vega, Ibagué',
    status: 'en_proceso',
    cover_photo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    photos: [],
    establishment: { id: '10', name: 'Refugio Patitas Sin Hogar', slug: 'refugio-patitas-sin-hogar', whatsapp_number: '573001234510' },
  },
];
