// Datos de demostración — reflejan supabase/seed.sql + 0005_pivot_preventivo.sql. Se usan
// como respaldo local (`isDemoMode`) mientras el proyecto Supabase real no está conectado,
// para poder construir y probar la UI de ambas apps desde ya. Reemplazar por datos reales
// apenas se provisione el backend (ver docs/NEXT_STEPS.md).
import type { EstablishmentWithDetails, EstablishmentHours, PreventiveEvent, PetDocument } from './types';

function fullWeekHours(establishmentId: string, is24h: boolean, sundayClosed = true): EstablishmentHours[] {
  return Array.from({ length: 7 }, (_, day_of_week) => ({
    id: `${establishmentId}-h${day_of_week}`,
    establishment_id: establishmentId,
    day_of_week,
    open_time: is24h ? '00:00' : '08:00:00',
    close_time: is24h ? '23:59' : '18:00:00',
    closed: !is24h && sundayClosed && day_of_week === 0,
  }));
}

// Directorio de demo: solo veterinaria/profesional — el nuevo alcance de PETAPP
// (comercio/fundación quedaron fuera del piloto, ver spec.md sección 2).
export const DEMO_ESTABLISHMENTS: EstablishmentWithDetails[] = [
  {
    id: '00000000-0000-4000-a000-000000000001',
    owner_id: null,
    name: 'Veterinaria Central Ibagué',
    slug: 'veterinaria-central-ibague',
    category: 'veterinaria',
    description: 'Atención general, urgencias y hospitalización. Más de 10 años atendiendo el centro de la ciudad.',
    address: 'Calle 15 # 3-20, Centro',
    city: 'Ibagué',
    lat: 4.4389,
    lng: -75.2322,
    phone: '6082601234',
    whatsapp_number: '573001234501',
    email: null,
    website: null,
    is_24_7: true,
    is_active: true,
    verification_status: 'verificado',
    verification_notes: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('1', true),
    services: [
      { id: 's1', establishment_id: '1', name: 'Consulta general', description: 'Valoración clínica completa', price_reference: 'desde $50.000', duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
      { id: 's2', establishment_id: '1', name: 'Vacunación', description: 'Esquema completo perros y gatos', price_reference: 'desde $35.000', duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: '00000000-0000-4000-a000-000000000002',
    owner_id: null,
    name: 'Clínica Veterinaria Pata Amiga',
    slug: 'clinica-pata-amiga',
    category: 'veterinaria',
    description: 'Consulta general, vacunación, cirugía y odontología veterinaria.',
    address: 'Carrera 5 # 42-10, Belén',
    city: 'Ibagué',
    lat: 4.4512,
    lng: -75.2101,
    phone: '6082605678',
    whatsapp_number: '573001234502',
    email: null,
    website: null,
    is_24_7: false,
    is_active: true,
    verification_status: 'verificado',
    verification_notes: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('2', false),
    services: [
      { id: 's3', establishment_id: '2', name: 'Cirugía menor', description: 'Esterilización y procedimientos ambulatorios', price_reference: 'desde $180.000', duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: '00000000-0000-4000-a000-000000000003',
    owner_id: null,
    name: 'Veterinaria y Urgencias 24H Tolima',
    slug: 'veterinaria-urgencias-24h-tolima',
    category: 'veterinaria',
    description: 'Atención de urgencias las 24 horas, todos los días.',
    address: 'Avenida Ambalá # 20-45',
    city: 'Ibagué',
    lat: 4.4601,
    lng: -75.2287,
    phone: '6082609876',
    whatsapp_number: '573001234503',
    email: null,
    website: null,
    is_24_7: true,
    is_active: true,
    verification_status: 'verificado',
    verification_notes: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('3', true),
    services: [
      { id: 's4', establishment_id: '3', name: 'Urgencia 24H', description: 'Atención inmediata cualquier hora del día', price_reference: 'desde $80.000', duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: '00000000-0000-4000-a000-000000000007',
    owner_id: null,
    name: 'Dra. Camila Rojas · Medicina Veterinaria',
    slug: 'dra-camila-rojas-veterinaria',
    category: 'profesional',
    description: 'Consulta a domicilio y medicina alternativa veterinaria.',
    address: 'Zona norte de Ibagué (atención a domicilio)',
    city: 'Ibagué',
    lat: 4.468,
    lng: -75.221,
    phone: '6082617788',
    whatsapp_number: '573001234507',
    email: null,
    website: null,
    is_24_7: false,
    is_active: true,
    verification_status: 'verificado',
    verification_notes: null,
    verified_at: new Date().toISOString(),
    verified_by: null,
    cover_image_url: null,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    hours: fullWeekHours('7', false),
    services: [
      { id: 's7', establishment_id: '7', name: 'Consulta a domicilio', description: 'Visita veterinaria en tu hogar', price_reference: 'desde $70.000', duration_minutes: null, is_active: true, created_at: new Date().toISOString() },
    ],
  },
];

const DAY = 24 * 60 * 60 * 1000;

// Demo del "buyer persona" del PDF: Camila Rojas, 34 años, Ibagué, 2 animales de compañía.
export const DEMO_PREVENTIVE_EVENTS: PreventiveEvent[] = [
  {
    id: 'pe1',
    pet_id: 'demo-pet-1',
    type: 'vacuna',
    title: 'Refuerzo antirrábico',
    due_date: new Date(Date.now() + 5 * DAY).toISOString().slice(0, 10),
    completed_at: null,
    reminder_sent_at: null,
    notes: 'Aplicar en Veterinaria Central Ibagué.',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pe2',
    pet_id: 'demo-pet-1',
    type: 'desparasitacion',
    title: 'Desparasitación trimestral',
    due_date: new Date(Date.now() + 20 * DAY).toISOString().slice(0, 10),
    completed_at: null,
    reminder_sent_at: null,
    notes: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pe3',
    pet_id: 'demo-pet-2',
    type: 'control',
    title: 'Control general anual',
    due_date: new Date(Date.now() - 3 * DAY).toISOString().slice(0, 10),
    completed_at: new Date(Date.now() - 3 * DAY).toISOString(),
    reminder_sent_at: null,
    notes: 'Completado en Clínica Veterinaria Pata Amiga.',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_PET_DOCUMENTS: PetDocument[] = [
  {
    id: 'pd1',
    pet_id: 'demo-pet-1',
    title: 'Carné de vacunación',
    document_url: 'https://example.com/demo/carnet-vacunacion.pdf',
    storage_path: null,
    document_type: 'carnet_vacunacion',
    uploaded_by: null,
    created_at: new Date().toISOString(),
  },
];
